### ISSUE TITLE
About Code

### ISSUE THREAD

**Issue by MontaEllis** [ming1993li/Instant3DCodes#2]
Great work! When will the code be released?

**Comment by xuxy09** [comment]
> Great work! When will the code be released?

Thanks for your interest. The code has been released.

**Comment by MontaEllis** [comment]
Thanks a lot! Will the training code be released?

**Comment by AlvinYH** [comment]
Thank the authors for releasing the code! I'm also wondering if the training code will be released, too.

**Comment by ming1993li** [comment]
Thank you very much for your interest. Please refer to the released code that includes our core proposal, i.e., a feedforward network for mapping text prompts to 3D representation, and understand that the preparation of the training code will take a much longer time.
