### ISSUE TITLE
weights of sdxl (turbo, lightning, hyper)

### ISSUE THREAD

**Issue by DiamondGlassDrill** [ming1993li/Instant3DCodes#3]
Thanks for this impressive work, is it possible to switch weights to the sdxl content generators, to increase image quality? As u currently use Sd 2.1
Cheers

**Comment by ming1993li** [comment]
Thank you for your interest. Our core idea is to present a feedforward network of connecting text prompts to 3D representation directly. The optimization is based on the SDS objective inspired by Stable Diffusion alike text-to-image diffusion models. Therefore, it is straightforward to replace SD 2.1 with SDXL for a high-quality 3D generation.
